name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: 
      - master
    tags:
      - '*'
jobs:
  macos:
    runs-on: ${{matrix.OS}}
    strategy:
      fail-fast: false
      matrix:
        OS: [macos-latest]
        SDK: ["macosx", "appletvsimulator", "iphonesimulator"]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pushd Example
        pod install
        popd  
    - name: Build and test
      run: |
        echo "Disabling modern build system as a workaround for target issue in Xcode 10+"
        USEMODERNBUILDSYSTEM="-UseModernBuildSystem=NO"
        if [ ${{ matrix.SDK }} == "macosx" ]; then
          SCHEME="ObjectiveCExample_macOS"
          SDK="macosx"
          DESTINATION="platform=macosx"
        fi
        if [ ${{ matrix.SDK }} == "appletvsimulator" ]; then
          SCHEME="ObjectiveCExample_tvOS"
          SDK="appletvsimulator"
          PLATFORM="tvOS Simulator"
          DEVICE="APPLE TV 4K (at 1080p)"
          DESTINATION="platform=$PLATFORM,name=$DEVICE"
        fi
        if [ ${{ matrix.SDK }} == "iphonesimulator" ]; then
          SCHEME="ObjectiveCExample_iOS"
          SDK="iphonesimulator"
          PLATFORM="iOS Simulator"
          DEVICE="iPhone 11 Pro Max"
          DESTINATION="platform=$PLATFORM,name=$DEVICE"
        fi

        # build and test
        CONFIGURATION="Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES"
        xcodebuild -workspace Example/ZipArchiveExample.xcworkspace -scheme $SCHEME -sdk $SDK -destination "$DESTINATION" -configuration $CONFIGURATION $USEMODERNBUILDSYSTEM test
